set dotenv-load := true
set positional-arguments := true

DATETIME := `TZ=UTC date '+%Y-%m-%d %H:%M:%S'`
STAGING := env('STAGING', 'crypto-1')
DOCKER_TAG := env('DOCKER_TAG', 'crypto/analytics-wf')
BASE_IMAGE := env('BASE_IMAGE', 'europe-west4-docker.pkg.dev/myexlab-ops/python/python:py-3.12.12-slim-trixie-feodor-uv')

UV_INDEX_MYEXLAB_USERNAME := env('UV_INDEX_MYEXLAB_USERNAME', '__token__')
UV_INDEX_PRIVATE_PASSWORD := env('UV_INDEX_PRIVATE_PASSWORD', '')

default:
    @just --list

# make new database migration with autogenerated changes
[group('maintenance')]
migration description='':
    @uv run --quiet \
    alembic revision \
        --autogenerate \
        --message \
        "{{ if description == '' {DATETIME} else {description} }}"

# apply database migrations
[group('maintenance')]
migrate:
    @uv run --quiet \
    alembic upgrade head

# clean bytecode and cache files, also useful to reset state of linters and type checkers
[group('maintenance')]
clean:
    @rm -rf .*_cache/
    @find . -type d -name "__pycache__" -exec rm -rf {} +
    @find . -type f -name "*.pyc" -exec rm -f {} +

# upgrade dependencies graph
[group('packaging')]
upgrade:
    @echo "upgrading mise dependencies.."
    @mise upgrade \
        --quiet \
        --yes \

    @echo "updating pre-commit hooks.."
    @uv run --quiet \
    pre-commit autoupdate \
        --config etc/pre-commit.yaml

    @echo "upgrading project (with development group) dependencies.."
    @uv sync \
        --refresh \
        --upgrade \
        --group development

    @echo "installed dependencies after upgrade:"
    @uv pip list

    @echo "locking updated dependencies.."
    @uv lock --upgrade

# publish package to repository
[group('packaging')]
publish:
	@rm -rf dist/ || true
	@uv build
	@uv run uv-publish --repo kain
	@rm -rf dist/ || true

# build docker image
[group('packaging')]
dock:
    @uv lock --quiet
    docker buildx build --load \
        --build-arg BASE_IMAGE="{{BASE_IMAGE}}" \
        --build-arg UV_INDEX_MYEXLAB_USERNAME="{{UV_INDEX_MYEXLAB_USERNAME}}" \
        --build-arg UV_INDEX_PRIVATE_PASSWORD="{{UV_INDEX_PRIVATE_PASSWORD}}" \
        -t "{{DOCKER_TAG}}" .

# production method of running the application
[group('project')]
run:
    @uv run --quiet main.py

# development method of running the application
[group('project')]
develop:
    @uv run development.py

# forward ports from remote environment using kubefwd; don't forgot run `gcloud auth login`
[group('project')]
ports:
    @echo " -> forward ports to {{STAGING}} environment"
    @sudo kubefwd svc -n temporal -n utils -n zitadel -n {{STAGING}}

# add development packages to environment when skipped
[group('maintenance')]
_development_packages:
    @uv sync --quiet --group development
