from pathlib import Path
from types import ModuleType
from typing import overload

__all__ = ("add_path", "optional", "required")

def get_module(path: str) -> tuple[ModuleType, tuple[str, ...]]: ...
def get_child(path: str, parent: object, child: str) -> object: ...
@overload
def import_object(path: str | bytes, something: None = None) -> object: ...
@overload
def import_object(path: str | bytes, something: object) -> object: ...
def cached_import(*args: object, **kw: object) -> object: ...
def required(path: str, *args: object, **kw: object) -> object: ...
def optional(path: str, *args: object, **kw: object) -> object: ...
def get_path(
    path: str | Path,
    root: str | Path | None = None,
) -> Path: ...
def add_path(path: str | Path, **kw: object) -> Path: ...
