from collections.abc import (
    Callable,
    Iterable,
    Iterator,
)
from functools import cache
from types import ModuleType
from typing import Any

__all__ = (
    "get_attr",
    "get_owner",
    "iter_inheritance",
    "iter_stack",
    "to_ascii",
    "to_bytes",
    "unique",
)

def class_of(obj: Any) -> type[Any]: ...
def is_collection(obj: Any) -> bool: ...
def is_iterable(obj: Any) -> bool: ...
def is_mapping(obj: Any) -> bool: ...
def is_primitive(obj: Any) -> bool: ...
def is_from_primitive(obj: Any) -> bool: ...
def is_from_builtin(obj: Any) -> bool: ...
def is_interactive() -> bool: ...
@cache
def _get_module_path_type(full: Any) -> tuple[bool | None, str]: ...
def is_internal(x: Any) -> bool: ...
def is_subclass(obj: Any, types: Any) -> bool: ...
def get_module(x: Any) -> ModuleType | None: ...
def get_module_name(x: Any) -> str | None: ...
def object_name(obj: Any, full: bool = True) -> str: ...
def pretty_module(obj: Any) -> str: ...
def source_file(
    obj: Any,
    template: str | None = None,
    **kw: Any,
) -> str | None: ...
def just_value(obj: Any, /, **kw: Any) -> str: ...
@cache
def is_imported_module(name: str) -> bool: ...
def get_mro(obj: Any, /, **kw: Any) -> tuple[Any, ...] | str: ...
def simple_repr(x: Any) -> bool | str | None: ...
def format_args_and_keywords(*args: Any, **kw: Any) -> str: ...
def who_is(obj: Any, /, full: bool = True, addr: bool = False) -> str: ...
def iter_stack(*args: Any, **kw: Any) -> Iterator[Any]: ...
def iter_inheritance(
    obj: Any,
    include: Any = None,
    exclude: Any = None,
    exclude_self: bool = True,
    exclude_stdlib: bool = True,
    reverse: bool = False,
) -> Iterator[Any]: ...
def _get_attribute_from_inheritance(
    obj: Any,
    name: str,
    **kw: Any,
) -> tuple[Any, Any]: ...
def get_owner(obj: Any, name: str, **kw: Any) -> Any | None: ...
def get_attr(obj: Any, name: str, default: Any = None, **kw: Any) -> Any: ...
def to_ascii(x: bytes | str, /, charset: str | None = None) -> str: ...
def to_bytes(x: bytes | str, /, charset: str | None = None) -> bytes: ...
def unique(
    iterable: Iterable[Any],
    /,
    key: Callable[[Any], Any] | None = None,
    include: Iterable[Any] | None = None,
    exclude: Iterable[Any] | None = None,
) -> Iterator[Any]: ...
